apiVersion: run.tanzu.vmware.com/v1alpha1 #TKG API endpoint 
kind: TanzuKubernetesCluster #required parameter 
metadata: 
  name: calc-k8-cluster #cluster name, user defined 
  namespace: calc #supervisor namespace 
spec: 
  distribution: 
    version: v1.20.2 #resolved kubernetes version 
  topology: 
    controlPlane: 
      count: 1 #number of control plane nodes 
      class: best-effort-small #vmclass for control plane nodes 
      storageClass: pacific-gold-storage-policy #storageclass for control plane
    workers: 
      count: 4 #number of worker nodes 
      class: best-effort-small #vmclass for worker nodes 
      storageClass: pacific-gold-storage-policy #storageclass for worker nodes