version: "3.4"
services:
  calcfrontend:
    container_name: vmw-calculator-frontend
    image: vmw-calculator-frontend:1.0.0
    build:
      context: ./../vmw-calculator-frontend
      # target: dev
    env_file:
      - ./../vmw-calculator-frontend/development.env
    volumes: 
      - ./../vmw-calculator-frontend/:/app/
      - /app/node_modules
    networks: 
      calc:
        ipv4_address: 172.20.0.3
    ports:
      - 3000:3000
      - 9229:9229
    restart: unless-stopped
    stdin_open: true

  addservice:
    container_name: vmw-calculator-addservice
    image: vmw-calculator-addservice:1.0.0
    build:
      context: ./../vmw-calculator-addservice
    networks: 
      calc:
        ipv4_address: 172.20.0.4
    ports:
      - 8081:8080
    restart: unless-stopped
    stdin_open: true
  
  substractservice:
    container_name: vmw-calculator-subtractservice
    image: vmw-calculator-subtractservice:1.0.0
    build:
      context: ./../vmw-calculator-subtractservice
    networks: 
      calc:
        ipv4_address: 172.20.0.5
    ports:
      - 8082:8080
    restart: unless-stopped
    stdin_open: true

  divisionservice:
    container_name: vmw-calculator-devisionservice
    image: vmw-calculator-divisionservice:1.0.0
    build:
      context: ./../vmw-calculator-divisionservice
    working_dir: /app
    volumes:
        - ./../vmw-calculator-divisionservice:/app
    networks: 
      calc:
        ipv4_address: 172.20.0.6
    ports:
      - 5001:5001
      - 5000:5000
    restart: unless-stopped
    stdin_open: true

  proxy:
    image: nginx
    container_name: vmw-calculator-nginx-proxy
    restart: unless-stopped
    networks: 
      calc:
        ipv4_address: 172.20.0.2
    ports: 
      - 80:80
      - 443:443
    volumes: 
      - ./../vmw-calculator-nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./../vmw-calculator-nginx/certs:/etc/nginx/certs
      - ./../vmw-calculator-nginx/logs:/var/log/nginx


networks:
  calc:
    # driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          #gateway: 172.20.0.1