version: "3.4"
services:
  calcfrontend:
    container_name: calc-frontend
    image: calc-frontend:1.0.0
    build:
      context: ./../calc-frontend
      target: dev
    env_file:
      - ./../calc-frontend/development.env
    volumes: 
      - ./../calc-frontend/:/app/
      - /app/node_modules
    networks: 
      calc:
        ipv4_address: 172.20.0.3
    ports:
      - 3000:3000
      - 9229:9229
    restart: unless-stopped
    stdin_open: true

  addservice:
    container_name: calc-addservice
    image: calc-addservice:1.0.0
    build:
      context: ./../calc-addservice
    networks: 
      calc:
        ipv4_address: 172.20.0.4
    ports:
      - 8081:8080
    restart: unless-stopped
    stdin_open: true
  
  substractservice:
    container_name: calc-substractservice
    image: calc-substractservice:1.0.0
    build:
      context: ./../calc-substractservice
    networks: 
      calc:
        ipv4_address: 172.20.0.5
    ports:
      - 8082:8080
    restart: unless-stopped
    stdin_open: true

  proxy:
    image: nginx
    container_name: calc-nginx-proxy
    restart: unless-stopped
    networks: 
      calc:
        ipv4_address: 172.20.0.2
    ports: 
      - 80:80
      - 443:443
    volumes: 
      - ./../calc-nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./../calc-nginx/certs:/etc/nginx/certs
      - ./../calc-nginx/logs:/var/log/nginx


networks:
  calc:
    # driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          #gateway: 172.20.0.1